# Streamlit Cloud Secrets Configuration
ENV = "production"
DEBUG = false
USE_DATABASE = false
DATABASE_URL = "sqlite:///telco.db"
MODEL_PATH = "models/saved/"
FEATURE_STORE_PATH = "data/features/"
LOG_LEVEL = "INFO"
SECRET_KEY = "streamlit-demo-secret-key"